# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Load RVM into a shell session *as a function*
if [[ -s "$HOME/.rvm/scripts/rvm" ]] ; then
 # First try to load from a user install
 source "$HOME/.rvm/scripts/rvm"
elif [[ -s "/usr/local/rvm/scripts/rvm" ]] ; then
 # Then try to load from a root install
 source "/usr/local/rvm/scripts/rvm"
else
 printf "ERROR: An RVM installation was not found.\n"
fi

# VIM mode
bindkey -v
bindkey "^R" history-incremental-search-backward

#FASD
PATH=$PATH:$HOME/fasd
eval "$(fasd --init auto)"

# Other bin files
PATH=$PATH:$HOME/local/bin

# For Xvfb and Jasmine
export DISPLAY=:0

# Customize to your needs...
# Execute the config files in .zsh.after
for config_file ($HOME/.zsh.after/**/*.zsh) source $config_file

# .zshrc is evaluated for every new zsh process,
# so when you call `tmux`, $PATH gets reevaluated,
# resulting in a messy $PATH that rvm will complain about
# until the next trigger of `cd`. This ensures that
# the $PATH is still compatible to rvm
# http://stackoverflow.com/questions/5838824/how-do-i-keep-my-rvm-gemset-while-using-tmux/6097090#6097090
cd .
