---
- get_url:
    url: https://sdk.cloud.google.com
    dest: /tmp/gcloud-install.sh

- name: Install gcloud
  shell: |
    bash /tmp/gcloud-install.sh \
      --disable-prompts \
      --install-dir={{home_dir}}/google-cloud-sdk
  args:
    creates: "{{home_dir}}/google-cloud-sdk"

- name: Create zsh hook directory
  file:
    path: "{{home_dir}}/.zsh.after/google-cloud-sdk"
    state: directory

- name: Add path hook
  template:
    src: path.zsh
    dest: "{{home_dir}}/.zsh.after/google-cloud-sdk/path.zsh"
